### ISSUE TITLE
Powershell script

### ISSUE THREAD

**Issue by trumad** [morosanuae/tw-icons#1]
Hi! Thank you for the icons. They've proved very useful in two TWs that I know of.

I read with great interest that you created a powershell script to import all the SVGs. Is this something you would be willing to share or post here in the repo? I have the dumb idea to put a collection of [clipart SVGs](https://thannymack.com/clipart/) into a tiddlywiki just to see how it would work with searching etc, and whatever script you wrote for the svg icons would probably work for this purpose also.

Thanks!

**Comment by morosanuae** [comment]
Hi @trumad

Every library has it's own script, because each library is different in terms of structure and content. So even though the script may work for your images it isn't an universal solution that works for anything out of the box. It must be adapted (modified) for each source first. Maybe I will publish the scripts in the future or at least try to make an almost universal solution but currently I don't have much spare time to do that.

**Comment by trumad** [comment]
Sorry, I forgot to reply to this. Thanks for your prompt reply. I'd be very happy with the scripts as-is, if you didn't mind sharing. I'm aware that they would need tweaking in order to work with my SVG collection and I don't mind that. Up to you though. Thanks again for this fantastic resource!
